### ISSUE TITLE
/r/postmarketOS subreddit theme

### ISSUE THREAD

**Issue by meganukebmp** [postmarketOS/artwork#6]
Was told to put this here as an issue.

I'm doing a css theme for the subreddit and got told to ask the community for opinions. http://imgur.com/a/UkuSL here are the two mockups I made.
One of them is currently on my test subreddit https://reddit.com/r/meganukebmp

**Comment by MartijnBraam** [comment]
I like the green background theme as the reddit theme personally.

**Comment by kskarthik** [comment]
green theme !

**Comment by ollieparanoid** [comment]
Thanks for making the issue! I guess it makes sense to make a PR for the CSS file of the winning theme, so we could add it to this repo.

**Comment by meganukebmp** [comment]
Yeah, for the most part. Its CSS and the images. They need to be uploaded with specific names. We can make a separate folder/repo for that.

**Comment by ollieparanoid** [comment]
I think a separate folder in this repo would be enough. So it looks like everyone likes the first one a bit more (with few exceptions). Should we make it the default one already, or do you want to [experiment](https://www.reddit.com/r/postmarketOS/comments/6z9u94/im_working_on_sprucing_up_the_sub_with_permission/dmtslmv/) a bit more?

**Comment by meganukebmp** [comment]
Ok, I'll wrap stuff up and give you a ready.

**Comment by meganukebmp** [comment]
Merged with upstream
